Add missing *body-parser* dependency.
There's a use of a dependency (body-parser) that's not declared.

Since npm flattens dependencies, it might usually work thanks to the dependency being also transitive. Using **pnpm** and installing this package locally instead of globally does make the error surface (*Error: Cannot find module 'body-parser'*).

The dependeny tree, as seen with `npm ls body-parser`:

```bash
myproject@1.0.0 /Users/someone/src/myproject
└─┬ elm-analyse@0.16.1
  ├─┬ express@4.16.3
  │ └── body-parser@1.18.2
  └─┬ express-ws@/express-ws/2.0.0/express@4.16.3
    └─┬ express@4.16.3
      └── body-parser@1.18.2
```

The usage is in (as of master when this issue was created, ed63e9f97b746632f7193237b6e5a30799b89e8a) 

`dist/app/server/app.js:22:31`,

It comes up when executing the tool (for example via `npx elm-analyze`).